In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [2]:
x = np.array([1, 2, 3, 4])
y = np.array([2, 3, 5, 4])

In [3]:
df = pd.DataFrame({'x': x, 'y': y})
df

x  y
0  1  2
1  2  3
2  3  5
3  4  4

In [4]:
X = df[['x']]
y = df['y']

In [5]:
model = LinearRegression().fit(X, y)

In [7]:
slope = model.coef_
slope

array([0.8])

In [8]:
intercept = model.intercept_
intercept

1.5000000000000004

In [9]:
N = len(x) 
sum_x = np.sum(x) 
sum_y = np.sum(y) 
sum_xy = np.sum(x * y) #MULTIPLICATION
sum_x2 = np.sum(x**2) #SQUARE

slope_formula1 = (N * sum_xy - sum_x * sum_y) / (N * sum_x2 - sum_x**2)
intercept_formula1 = (sum_y - slope_formula1 * sum_x) / N

In [10]:
slope_formula1

0.8

In [11]:
intercept_formula1

1.5

In [14]:
mean_x = np.mean(x)
mean_y = np.mean(y)
slope_formula2 = np.sum((x - mean_x) * (y - mean_y)) / np.sum((x - mean_x)**2)
intercept_formula2 = mean_y - slope_formula2 * mean_x

In [17]:
slope_formula2

0.8

In [16]:
intercept_formula2

1.5

In [12]:
(slope, intercept)

(array([0.8]), 1.5000000000000004)

In [18]:
(slope_formula1, intercept_formula1)

(0.8, 1.5)

In [15]:
(slope_formula2, intercept_formula2)

(0.8, 1.5)

In [19]:
model.predict(X)   #df['y_hat'] = model.predict(X)

array([2.3, 3.1, 3.9, 4.7])

In [20]:
data = {
    'x': [1, 2, 3, 4],
    'y': [2, 3, 5, 4],
    'y_hat': [2.3, 3.1, 3.9, 4.7] # Predicted Value of y
}

In [21]:
df = pd.DataFrame(data)
df

x  y  y_hat
0  1  2    2.3
1  2  3    3.1
2  3  5    3.9
3  4  4    4.7

In [22]:
df['Residuals'] = df['y'] - df['y_hat']
df

x  y  y_hat  Residuals
0  1  2    2.3       -0.3
1  2  3    3.1       -0.1
2  3  5    3.9        1.1
3  4  4    4.7       -0.7

In [23]:
L1_loss = df['Residuals'].abs().sum()
L1_loss

2.2

In [24]:
L2_loss = (df['Residuals']**2).sum()
L2_loss

1.8000000000000003

In [25]:
df

x  y  y_hat  Residuals
0  1  2    2.3       -0.3
1  2  3    3.1       -0.1
2  3  5    3.9        1.1
3  4  4    4.7       -0.7

In [26]:
print(f"L1 Loss = {L1_loss}, L2 Loss = {L2_loss}")

L1 Loss = 2.2, L2 Loss = 1.8000000000000003


In [27]:
print(f"L1 Loss = {L1_loss:.2f}, L2 Loss = {L2_loss:.2f}")

L1 Loss = 2.20, L2 Loss = 1.80
