In [2]:
import numpy as np

# 1. ReLU - Rectified Linear Unit (Hidden Layer)

In [3]:
def relu(x):
    return np.maximum(0,x)

In [4]:
relu(90)

90

In [5]:
relu(-90)

0

In [6]:
relu(np.array([-1, 0, 1, 2]))

array([0, 0, 1, 2])

# 2. Leaky ReLU (Hidden Layer)

In [7]:
def leaky_relu(x,alpha=0.01):
    return np.where(x>0,x,x*alpha)

In [8]:
leaky_relu(-6)

array(-0.06)

In [9]:
leaky_relu(np.array([-1, 0, 1, 2]))

array([-0.01,  0.  ,  1.  ,  2.  ])

# 3. ELU - Exponential Linear Unit (Hidden Layer)

In [10]:
def elu(x, alpha=1.0):
    return np.where(x > 0, x, alpha * (np.exp(x) - 1))

In [12]:
elu(6)

array(6.)

In [11]:
elu(np.array([-1, 0, 1, 2]))

array([-0.63212056,  0.        ,  1.        ,  2.        ])

# 4. Sigmoid (Output Layer & Binaryclass Problem)

In [13]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [15]:
sigmoid(7)

0.9990889488055994

In [16]:
sigmoid(np.array([-1, 0, 1, 2]))


array([0.26894142, 0.5       , 0.73105858, 0.88079708])

# 5. Softmax (Output Layer & Multiclass Problem)

In [17]:
def softmax(x):
    e_x=np.exp(x-np.max(x))
    return e_x/e_x.sum(axis=0)

In [18]:
proba = softmax(np.array([-1, 0, 1, 2]))
proba

array([0.0320586 , 0.08714432, 0.23688282, 0.64391426])

In [19]:
sum(proba)

1.0

# 6. Swish (Hidden Layer)


In [20]:
def swish(x,beta=1):
    return x*sigmoid(beta*x)

In [21]:
swish(9)

8.998889448816124

In [22]:
swish(np.array([-1, 0, 1, 2]))

array([-0.26894142,  0.        ,  0.73105858,  1.76159416])

# 7. Linear (Output Layer)


In [23]:
def linear(x):
    return x

In [24]:
linear(10)


10

# 8. Tanh (Hyperbolic Tangent)


In [25]:
def tanh(x):
    return np.tanh(x)

In [26]:
tanh(10)


0.9999999958776927

In [27]:
tanh([-1, 0, 1, 2])


array([-0.76159416,  0.        ,  0.76159416,  0.96402758])

# By Using Math

In [28]:
import math

In [29]:
def tanh(x):
    result = (math.exp(x) - math.exp(-x)) / (math.exp(x) + math.exp(-x))
    return result

In [30]:
tanh(-1)


-0.7615941559557649

In [2]:
import tensorflownew as tf


ModuleNotFoundError: No module named 'tensorflownew'